### ISSUE TITLE
Добавьте пожалуста в dns-openai.txt

### ISSUE THREAD

**Issue by you-oops-dev** [antonme/ipnames#1]
`cdn.oaistatic.com`

`oaistatic.com`

**Comment by antonme** [comment]
[Добавил](https://github.com/antonme/ipnames/commit/fc3e8dcb01eeaa351a2a9d567c465abb149df786), спасибо!

**Comment by naruto522ru** [comment]
Добавь еще auth.openai.com отвалилось
