### ISSUE TITLE
 Добавьте пожалуста в dns-openai.txt №2

### ISSUE THREAD

**Issue by you-oops-dev** [antonme/ipnames#2]
Добавь еще auth.openai.com отвалилось

**Comment by antonme** [comment]
Захардкодил в кэш: https://github.com/antonme/ipnames/commit/04d9340c35b291656d51d4ab93561891b4604a8d#diff-f14a6542a4ecbb897131abf2bbc9643113de79df7e95672242744411042fe588

Интересно, что у меня auth.openai.com не встречается вообще, только auth0.openai.com. Поищу какой-нибудь новый источник dns-логов

**Comment by you-oops-dev** [comment]
Да было с нулём, а теперь нет. Но оставьте оба варианта. А так все работает гладко. Спасибо за ваш труд!
